File = open("main.cpp", "w")

File.write("#include <iostream>\n")
File.write("using namespace std;\n")
File.write("int main()\n")
File.write("{\n")
File.write("\tcout << \"")
inputname = input("Enter output string: ")
File.write(inputname)
File.write("\";\n")
File.write("}")
